# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'meRPG' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for meRPG

  target 'meRPGTests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

end

target 'meRPG-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for meRPG-tvOS

  target 'meRPG-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
